Normal Types Page
jMonkeyEngine/wiki pull request #173
Opened 2023-11-08 20:14 UTC by codex128

This PR creates a page explaining the usage of the NormalType parameter in Lighting.j3md and PBRLighting.j3md according to [Issue 2143](https://github.com/jMonkeyEngine/jmonkeyengine/issues/2143) in the main JME repo.

2023-11-09 07:37 UTC, riccardobl requested changes

2023-11-09 07:37 UTC, riccardobl commented on docs/modules/core/pages/material/normal-types.adoc
> +* DirectX (known as DirectX-Style)
Could you please include Y+ and Y- as in the draft? These styles are frequently referenced this way, so having them at the start of the page would be a helpful addition

2023-11-09 07:37 UTC, riccardobl commented on docs/modules/core/pages/material/normal-types.adoc
> +This can cause shading to not look quite right if a shader tries to use OpenGL convention on a normal map designed for DirectX.
Can you replace shaders with materials?

2023-11-09 07:37 UTC, riccardobl commented on docs/modules/core/pages/material/normal-types.adoc
> +```
Should add a note that says you don't need to do it when loading a model with the asset loader

2023-11-09 07:37 UTC, riccardobl commented on docs/modules/core/pages/material/normal-types.adoc
> +
This is not always the case, those are the input normal type, what is outputted by blender, for example, depends on the addon used. 
Also, these programs are not commonly used to generate normalmaps as far as i know.
If we need to add a section with programs, we should probably show the setting window for substance painter or other similar software

2023-11-10 19:40 UTC, riccardobl commented
Looks good, thanks.
Do we need to add this to a menu or something?

2023-11-10 20:37 UTC, codex128 commented
I think so, but I don't know how to.

2023-11-24 11:18 UTC, richardTingle commented
@codex128 See the file docs/modules/core/nav.adoc. You can see the nav being built there (other files build other parts of the nav but I think thats the one you want). You can see that the parentage is defined by the depth of the *s and there is a simple file path and name specified for the nav item.

I think your xref would be `xref:material/normal-types.adoc`

So e.g. 

** xref:material/normal-types.adoc[Your title does here]

But you'd need to decide exactly where it goes

2023-11-28 01:59 UTC, codex128 commented
Ah, thanks! I will look into that when I get the chance.

2025-04-25 09:05 UTC, richardTingle commented
@codex128 Are you still looking to add this? This looks like a useful article. Just needs to be added to the nav and I'll merge it

2025-04-25 11:16 UTC, codex128 commented
I had to fix up the PR due to a broken commit, but this is ready for merging now.

2025-04-25 12:20 UTC, merged

2025-04-25 12:20 UTC, richardTingle commented
Thanks @codex128. I've merged